# -*- coding: utf-8 -*-
"""Activity 2_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZ0F7BSGtQWnAVN9D9imvMYGMKnich9p

#Activity 2.1: Trace Execution of Conditional Code Snippets
○ Format: Individual work with peer discussion/instructor led review.

○ Instructions: Provide several code snippets with if/elif/else and logical operators.
Students must trace the execution step-by-step for given input values and determine
the final output.

○ Purpose: Reinforce understanding of how conditions are evaluated and how the
program flow changes.

#Sample Snippets (for Handout/Projection):
#Python
"""

# Snippet A
score = 85
if score >= 90:
  grade = "A";
elif score >= 80:
  grade = "B";
else:
  grade = "C";
print(f"Grade: {grade}")

#อธิบายโค้ด
#กำหนดให้ score มี type เป็น integer ซึ่งเท่ากับ 85
#หลังจากนั้นเช็คเงื่อนไข if ถ้า score มากกว่า หรือ เท่ากับ 90 จะได้ grade = A
#ถ้าไม่ตรงเงื่อนไขจะเช็ค elif ต่อถ้า หแนพำ มากกว่า หรือ เท่ากับ 80 จะได้ grade = b
#ถ้าไม่ตรงเงื่อนไขทั้งสองเงื่อนไขด้านบน จะมาที่ else ซึ่งจะได้ grade = c
#หลังจากนั้นก็จะ print grade ออกมา
#ซึ่งภ้ากำหนด score เป็น 85 ผลลัพธ์ที่ได้คือ Grade: B

# Snippet B
temp = 25
is_raining = True
if temp > 20 and not is_raining:
  print("Perfect day for a picnic!")
elif temp <= 20 or is_raining:
  print("Stay indoors or bring an umbrella.")
else:
  print("Unsure about the weather.")

#อธิบายโค้ด
#กำหนดให้ temp มี type เป็น integer ซึ่งเท่ากับ 25
#is_raining มี type เป็น boolean มีค่าเป็น True
#หลังจากนั้นจะเช็คเงื่อนไข if ซึ่งมี not อยู่ด้านหน้า is_raining
#ทำให้ค่าความจริงของ is_raining เปลี่ยนไป โดยเปลี่ยนจาก True เป็น False
#และกำหนดให้ temp > 20 ซึ่งตอนนี้ temp เป็น 25 ทำให้ได้เป็น true และนำทั้งสองอย่างนี้มา and กัน
#ซึ่ง True and False จะได้ False ทำให้ไม่ได้เข้าไปใน if โดยจะเลื่อนลงมาที่ elif แทน
#โดย elif มีเงื่อนไขคือ temp <= 20 ซึ่ง temp ของเราเป็น 25 จะได้ False
#โดยเชื่อมกับ is_raining ที่มีค่าเป็น True ด้วย or ทำให้ False or True ได้เป็น True ซึ่งตรงเงื่อนไข
#ทำให้ได้เข้าไป โดยจะแสดงผลข้อความว่า "Stay indoors or bring an umbrella." ออกมา

# Snippet C
age = 17
has_license = True
if age >= 18:
  if has_license:
    print("You can drive legally.")
  else:
    print("You need a license to drive.")
else:
  print("You are too young to drive.")


#อธิบายโค้ด
#กำหนดให้ age มี type เป็น integer มีค่าเท่ากับ 17
#ให้ has_license มี type เป็น boolean มีค่าเป็น True
#แล้วเช็คเงื่อนไข if โดยมีเงื่อนไขว่า age >= 18 ซึ่งเป็น False ทำให้ข้ามลงมาที่ else
#และแสดงผลข้อความว่า "You are too young to drive." ออกมา