# -*- coding: utf-8 -*-
"""Activity 2_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUbslPX-0jnMx1Vj0fBpWLeNFepVCW8e

#Activity 2.2: Design a Simple &quot;Choose Your Own Adventure&quot; Text Game
○ Format: Small groups (2-3 students).
○ Instructions:
1. Brainstorm: As a group, come up with a very short &quot;choose your own adventure&quot;
story concept (e.g., entering a haunted house, exploring a forest).
2. Design: Outline 2-3 decision points in your story. For each decision, determine 2-3
possible choices and their outcomes.
3. Pseudo-code/Outline: Write down the basic input() prompts and the if-elif-else
structure needed to implement your story&#39;s decisions. You don&#39;t need to write full
Python code yet, just the logic.

4. Share: Each group presents their story concept and their conditional logic outline
to the class.
○ Purpose: Apply conditional logic to a creative, problem-solving scenario, fostering
design thinking and collaboration before coding.

# Rich Game Simulator

คำอธิบาย : เกมจำลองการไต่เต้าเพื่อไปเป็น CEO โดยเริ่มต้นจาก 0
"""

print("Rich Game Simulator")
start = input("Start game (y/n) : ")
if start == "y":
  print("\n----------------------------------------------------\n")
  name = input("Your name : ")
  print(f"\n{name} อายุ 23 ปี เป็นคนธรรมดาทั่วไป ที่ไม่มีงานทำ และตอนนี้มีเงินทั้งหมด 10,000 บาท")
  print("จงเลือก\n 1.เอาเงินทั้งหมด 10,000 บาท ไปซื้อลอตเตอรี่\n")
  print("2.นำเงินไปเปิดร้านขายไส้กรอก\n")
  print("3.ไปยื่นเรซูเม่ สมัครงานกับบริษัทต่างๆ\n")
  print("4. นำเงินไปลงทุนในหุ้น\n")
  print("5.นำไปซื้นตั๋วเที่ยวบินไปหา MrBeast\n")
  print("6. นำไปซื้อตั๋วเที่ยวบินไป อินเดีย\n")
  ch = input("คุณเลือก (ตอบแค่ตัวเลข) : ")
  choose = int(ch)
  if choose == 1:
    print("ยินดีด้วย คุณถูกลอตเตอรี่จำนวน 0 ใบ ทำให้เงินคุณเหลือ 0 บาท\n")
    print("ส่งผลให้คุณไม่มีเงินซื้อข้าวกิน\n")
    print("จงเลือก\n 1.แย่งข้าวสุนัขกิน\n2.ปล้นธนาคาร\n3.ไปเป็นขอทาน\n")
    ch1 = input("คุณเลือก (ตอบแค่ตัวเลข) : ")
    choose1 =int(ch1)
    if choose1 == 1:
      print("You dead!\n เนื่องจากโดนสุนัขรุมกัด")
      print("\nBad Ending")
    elif choose1 == 2:
      print("คุณโดนตำรวจจับ")
      print("\nBad Ending")
    else:
      print("มีมหาเศรษฐีผ่านมา โยนเงินให้คุณ 1,000,000 ดอลล่า\n")
      print("หลังจากนั้นคุณก็ได้ใช้เงินอย่างมีความสุข")
      print("\nHappy Ending")
  elif choose == 2:
    print("เนื่องจาก บริเวณที่คุณอยู่ เป็นหมู่บ้านส่งเสริมสุขภาพ ทำให้ไม่มีใครซื้อไส้กรอกของคุณ")
    print("\nBad Ending")
  elif choose == 3:
    print("มีบริษัทเรียกคุณไปสัมภาษณ์ ดังนี้\n 1.Slowwork 2.I have GPU 3.Ananhan")
    ch2 = input("คุณเลือก (ตอบแค่ตัวเลข) : ")
    choose2 = int(ch2)
    if choose2 == 1:
      print("คุณผ่านสัมภาษณ์\n แล้วคุณก็มีงานทำ มีเงินเดือน เดือนละ 25,000 บาท")
      print("\nHappy Ending")
    elif choose2 == 2:
      print("คุณไม่ผ่านสัมภาษณ์\n เนื่องจากคุณไม่มีความรู้เกี่ยวกับอุปกรณ์คอมพิวเตอร์")
      print("\nBad Ending")
    else:
      print("คุณผ่านสัมภาษณ์\n หลังจากนั้นคุณได้รับเชิญไปออกรายการ Where are you! ที่อินเดีย")
      print("\nพอคุณไปถึงอินเดียคุณก็หลงทาง กระเป๋าหาย passport หาย ไม่มีอะไรติดตัวเลย")
      print("\nBad Ending")
  elif choose == 4:
    print("ลงทุนผิด เงินคุณเหลือ 0 บาท เนื่องจากคุณไม่มีความรู้เกี่ยวกับหุ้น")
    print("\nBad Ending")
  elif choose == 5:
    print("คุณได้พบกับ MrBeast แล้วเขาก็พูดว่า\n")
    print("ผมจะให้เงินคุณ 1,000,000 ดอลล่า ถ้าคุณลงไปว่ายน้ำกับฉลาม 10 ตัวในบ่อ\n")
    print("คุณกระโดดลงไปในบ่อ แล้วถูกฉลามกิน")
    print("\nBad Ending")
  else:
    print("คุณไปถึงอินเดียอย่างปลอดภัย\n")
    print("คุณเจอปรามาจารย์ด้านการทำโรตี หลังจากนั้นคุณก็ฝากตัวเป็นศิษย์กับเขา\n")
    print("10 ปีผ่านไป\n")
    print("คุณได้ไปเข้าร่วมการแข่งขัน การทำโรตีชิงแชมป์โลก และคุณก็ชนะ\n")
    print("ทำให้คุณได้เป็น แชมป์โลกโรตี")
    print("\nHappy Ending")
else:
  print("-------------------------------------")