# -*- coding: utf-8 -*-
"""LAB2_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0QRFDbm6pDel_1RUilJZJmDw5WWK4l5

#Lab 2.2: Simple Decision-Making Program (Movie Rating)
○ Objective: Students will create a program that recommends a movie rating based on
the user&#39;s age, demonstrating nested or chained conditionals.
○ Tasks (Common for Local &amp; Colab):
1. Create a new Python file (lab2_2.py) or Colab code cell.
2. Prompt the user to enter their age. Convert it to an integer.
3. Implement the following logic:

■ If age is less than 5: Print &quot;You&#39;re too young for movies! Enjoy cartoons.&quot;

■ If age is 5 to 12 (inclusive): Recommend &quot;G-rated or PG-rated movies.&quot;

■ If age is 13 to 17 (inclusive): Recommend &quot;PG-13 or R-rated (with parental
guidance).&quot;

■ If age is 18 or older: Recommend &quot;Any movie rating.&quot;
"""

age = input("Input your age : ")
age_int = int(age)
if age_int < 5:
  print("\nYou're too young for movies! Enjoy cartoons.")
elif age_int >=5 and age_int <=12:
  print("\nG-rated or PG-rated movies.")
elif age_int >= 13 and age_int <=17:
  print("\nPG-13 or R-rated (with parental guidance).")
else:
  print("\nAny movie rating.")

"""#Challenge: Add a secondary prompt: &quot;Do you like action movies? (yes/no)&quot;.
If the age is 18 or older AND they like action, print &quot;You might enjoy the latest action
blockbuster!&quot; (This requires a nested if or more complex logical and conditions).
"""

action_movie = input("Do you like action movies? (yes/no) : ")
if action_movie == "yes" and age_int >= 18:
  print("\nYou might enjoy the latest action blockbuster!")