# -*- coding: utf-8 -*-
"""LAB2_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIUCi6GtvQFrAwyY-ln3uqeKJY2YuiQk

#Lab 2.1: Number Classifier
○ Objective: Students will write a script to classify a user-provided integer as positive,
negative, or zero, and also check if it&#39;s even or odd.

○ Tasks (Common for Local &amp; Colab):

1. Create a new Python file (lab2_1.py) or Colab code cell.
2. Prompt the user to enter an integer using input().
"""

num = input("input your number : ")
print(num)

"""3. Convert the input to an integer."""

num_int = int(num)
print(f"Your type : {type(num_int)}")

"""4. Use if-elif-else to determine if the number is positive, negative, or zero. Print the
classification.
"""

if num_int < 0:
  print("Your number < 0")
elif num_int > 0:
  print("Your number > 0")
else:
  print("Your number = 0")

"""5. Use an if-else statement to determine if the number is even or odd. Print the result."""

if (num_int%2) == 0:
  print("Your number is even number")
else:
  print("Your number is odd number")

"""#Challenge"""

num = input("input your number : ")

def check(input_num):

  try:
    num_int = int(input_num)
    print(f"Your type : {type(num_int)}")
    return 0

  except ValueError:
    print(f"Your type : {type(input_num)}")
    print("Your input is not a integer number")
    return 1

def number(number):
  ch = check(number)
  if ch == 0:
    num = int(number)
    if num < 0:
      print("Your number < 0")
    elif num > 0:
      print("Your number > 0")
    else:
      print("Your number = 0")
    print("--------------------------------------------------")
    if (num%2) == 0:
      print("Your number is even number")
    else:
      print("Your number is odd number")

number(num)