# -*- coding: utf-8 -*-
"""Activity 3.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xae94xTNRr77mh9gZ0BE598pf49tpEl4

# Activity 3.1: Debugging Infinite Loops & Loop Logic Errors
Format: Individual or pair work, followed by class discussion/demonstration.
Instructions: Provide students with several buggy code snippets containing:
An infinite while loop (missing update of loop control variable).
A for loop that doesn't produce the desired range (incorrect range() arguments).
A loop where break or continue is used incorrectly.
Students must identify the bug, explain why it happens, and fix the code.
Purpose: Develop critical debugging skills, understand common loop pitfalls.
"""

#Sample Buggy Snippets (for Handout/Projection):
# Buggy Snippet A: Infinite Loop
counter = 0
while counter < 5:
  print(counter)
# ลูปนี้จะไม่สิ้นสุด เพราะว่าค่าของ counter เป็น 0 ไม่เปลี่ยนแปลงทำให้ลูปไปเรื่อยๆ ทางแก้ควรมี count = count + 1 หรือตัวอื่นๆ
# เพื่อเป็นตัวกำหนดจำนวน loop

# Buggy Snippet B: Incorrect Range
for i in range(1, 5): # Goal: print 1, 2, 3, 4, 5
  print(i)
#ไม่ถูกต้อง เนื่องจาก range(1, 5) จะ print แค่ 1 2 3 4 ไม่เอาตัวสุดท้ายมาด้วย แก้โดยเพิ่มเป็น range(1, 6)

# Buggy Snippet C: Misplaced Break
for char in "hello":
  if char == 'l':
    print("Found 'l', stopping!")
    break
    print(char) # This will print 'h', 'e', 'l' then break
#ไม่ถูกต้องเนื่องจาก print(char) อยู่ใน if char == 'l' และอยู่ข้างล่าง break ทำให้ไม่ทำงาน
#วิธีแก้คือเอา print(char) มาวางไว้ นอก if char == 'l':

"""#Code ที่ถูกต้อง

"""

# Buggy Snippet A: Infinite Loop
counter = 0
while counter < 5:
  print(counter)
  counter = counter +1


print("---------------------------------------")
# Buggy Snippet B: Incorrect Range
for i in range(1, 6): # Goal: print 1, 2, 3, 4, 5
  print(i)

print("------------------------------------------")
# Buggy Snippet C: Misplaced Break
for char in "hello":
  if char == 'l':
    print("Found 'l', stopping!")
    break
  print(char)