# -*- coding: utf-8 -*-
"""Activity 3.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pD-u957TCuao_UH7iWGBbI-OSboL-acP

# Activity 3.2: Pattern Printing with Nested Loops
Format: Individual creative coding challenge.
Instructions: Ask students to write Python code using nested for loops to print simple ASCII art patterns.

1. A square of asterisks:
"""

num = int(input("Input your size :"))
for i in range(num):
  for j in range(num):
    print("*",end = "")
  print("")

"""2. A right-angled triangle of asterisks:"""

num = int(input("Input your size :"))
k = 1
for i in range(num):
  for j in range(k):
    print("*", end = "")
  k = k + 1
  print("")

"""3. Challenge: An inverted right-angled triangle or a pyramid.

Purpose: Reinforce understanding of nested loops and the relationship between loop variables and printed output. Encourages algorithmic thinking and problem-solving.
"""

num = int(input("Input your size :"))
k = num
for i in range(num):
  for j in range(k):
    print("*", end = "")
  k = k - 1
  print("")