# -*- coding: utf-8 -*-
"""Lab3.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVM02vFL8LlGJtgHJBcPtMGchmXB9FRf

# New SectionLab 3.1: โปรแกรมสร้างสูตรคูณ (Multiplication Table Generator)
วัตถุประสงค์: ให้นักศึกษาใช้ลูป for (และอาจใช้ลูปซ้อนลูป) เพื่อสร้างแม่สูตรคูณสำหรับตัวเลขที่กำหนด หรือสร้างตารางสูตรคูณตามช่วงตัวเลขที่ระบุ

# Part 1: ตารางสูตรคูณแม่เดียว (Single Number Table):
รับค่า (Prompt) จากผู้ใช้ให้กรอกตัวเลขที่ต้องการ (เช่น เลข 7)
ใช้ลูป for ร่วมกับ range(1, 13) เพื่อพิมพ์แม่สูตรคูณของเลขนั้นตั้งแต่คูณ 1 ถึง 12
ตัวอย่างผลลัพธ์ (Output) สำหรับเลข 7:Plaintext7 x 1 = 7
7 x 2 = 14
...
7 x 12 = 84
"""

num = int(input("Input your number : "))
m = 1
n = 1
for i in range(1,13):
  result = num*i
  print(f"{num} x {i} = {result}")

"""# Part 2: ตารางสูตรคูณแบบเต็ม (Full Multiplication Grid) - โจทย์ท้าทาย/ส่วนขยาย:
ใช้ลูป for แบบซ้อนกัน (Nested loops) เพื่อพิมพ์ตารางสูตรคูณขนาด 12x12
จัดรูปแบบผลลัพธ์ให้สวยงามและเป็นระเบียบ (เช่น ใช้คำสั่ง print(f"{i*j:4d}", end="") และใช้ print() เปล่า ๆ หลังจากจบลูปในแต่ละแถวเพื่อเว้นบรรทัด)
คำใบ้ (Hint): ลูปนอก (Outer loop) ใช้สำหรับวนซ้ำตามแถว (Rows) ส่วนลูปใน (Inner loop) ใช้สำหรับวนซ้ำตามคอลัมน์ (Columns)
ตัวอย่างผลลัพธ์
   1   2   3   4   5   6   7   8   9  10  11  12
   2   4   6   8  10  12  14  16  18  20  22  24
   3   6   9  12  15  18  21  24  27  30  33  36
   4   8  12  16  20  24  28  32  36  40  44  48
...
  12  24  36  48  60  72  84  96 108 120 132 144
"""

for i in range (1,13):
  for j in range(1,13):
    num = i*j
    print(f"{num:4d}", end="")
  print("")