# -*- coding: utf-8 -*-
"""Lab3.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnJLMtvunspZZS4S_2AowWT2gKRjlDlV

# Lab 3.2: โปรแกรมการนับถอยหลัง & เกมทายตัวเลข (Countdown & User Guessing Game)
วัตถุประสงค์: ให้นักศึกษาฝึกใช้งานลูป while สำหรับการนับถอยหลังและสร้างเกมทายตัวเลขอย่างง่าย รวมถึงการนำคำสั่ง break มาใช้เพื่อออกจากลูปก่อนกำหนด

# Part 1: โปรแกรมตัวนับถอยหลัง (Countdown Timer):
รับค่าจากผู้ใช้ให้กรอกตัวเลขเริ่มต้นสำหรับนับถอยหลัง
ใช้ลูป while เพื่อทำการนับถอยหลังลดลงทีละ 1 จากเลขนั้นไปจนถึง 0 และพิมพ์ตัวเลขแต่ละตัวออกมา
หลังจากจบลูป ให้พิมพ์คำว่า "Blast off!" (จุดระเบิดยาน!)
เช่น ถ้าป้อน 5 ผลลัพธ์จะเป็น
5
4
3
2
1
0
Blast off!
"""

num = int(input("Input your number"))
while num >= 0:
  print(num)
  num = num -1
print("Blast off!")

"""# Part 2: เกมทายตัวเลขอย่างง่าย (Simple Guessing Game) + Challenge:
กำหนดตัวเลขลับขึ้นมา 1 ตัว (เช่น secret_number = 42)
ใช้ลูป while True เพื่อสุ่มถามให้ผู้ใช้ทายตัวเลขอย่างต่อเนื่อง
ถ้าตัวเลขที่ทาย น้อยเกินไป ให้พิมพ์ว่า "Too low! Try again."
ถ้าตัวเลขที่ทาย มากเกินไป ให้พิมพ์ว่า "Too high! Try again."
ถ้าตัวเลขที่ทาย ถูกต้อง ให้พิมพ์ว่า "Congratulations! You guessed it!" และใช้คำสั่ง break เพื่อออกจากลูป
โจทย์ท้าทาย (Challenge): เพิ่มการจำกัดจำนวนครั้งในการทาย (เช่น ทายได้สูงสุด 5 ครั้ง) โดยให้ใช้ break หรือเงื่อนไข else ของลูป while เมื่อโควตาการทายหมดลง
ตัวอย่างผลลัพธ์
Guess the number: 20
20 is Too low! Try again.

Guess the number: 60
60 is Too high! Try again.

Guess the number: 42
Congratulations! You guessed it!
"""

import random
num_secret = random.randint(1,100)
count = 5
while count!= 0:
  num = int(input("Guess the number: "))
  if num == num_secret:
    print("Congratulations! You guessed it!")
    break
  elif num > num_secret:
    print(f"{num} is Too high! Try again.")
  else:
    print(f"{num} is Too low! Try again.")
  count = count -1
  print(f"Remaining guesses : {count}\n")
  if count == 0:
    print(f"You lose! Number secret is {num_secret}")